version: "3.9"

services:
  app:
    build: .
    image: ai-briefing-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_DATABASE_URL: postgresql+asyncpg://briefing:briefing@postgres:5432/briefing
    ports:
      - "8000:8000"
      - "5173:8000"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: briefing
      POSTGRES_USER: briefing
      POSTGRES_PASSWORD: briefing
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U briefing -d briefing"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

volumes:
  pgdata:
